<p>This  website is dedicated to finding the right lender to fit your personal needs. We  are an ongoing partner in the pursuit of financial products and services that  make your life better. Our unique program matches the needs of our  customers with the right lenders for installment loans, payday loans, and  merchandise credit lines. We maintain a database of these different type  lenders, and show your profile to the best lenders for your unique situation.  You create one simple online profile, and we search our entire network in your  behalf.</p>
<p>Not  all credit providers operate in all states or accept all types of credit.  Not all lenders can provide the advertised amount. Some lenders require a  credit report to make their credit decision, while others do not, so we ask you  to rate your credit. Here is a brief description of our credit rating  system based on your FICO score.</p>
<p align="center"><strong> Excellent 720+ Good 650 – 719  Average 600 –  649 Poor &lt;600</strong></p>
<p> </p>
<p><strong><u>Installment  loans</u></strong><br />
    <br />
    An <strong>installment  loan</strong> is a loan that is repaid over time with a set number of scheduled  payments. The term of loan may be as little as a few months and as long as 30  years. A mortgage, for example, is one type of installment loan.<br />
    The term is most  strongly associated with traditional consumer loans, originated and serviced  locally, and repaid over time by regular payments of principal and interest. <br />
    Each lender is  required to provide you, the consumer, with all costs associated to be expressed  as an annual percentage rate of interest (APR). This information will  include the identity of the creditor, the amount financed, the itemization of  amount financed, the finance charge, the annual percentage rate, your payment  schedule, and your total number of payments. Your interest rate will vary  depending upon which product you accept from which lender -- Currently this  range is anywhere from 6% up to 25% APR on installment loans ~ but check with  your individual lender and what they are offering you, as this fluctuates with  market conditions and your credit profile. In addition, the Federal Equal  Credit Opportunity Act prohibits creditors from discriminating against  applicants on the basis of color, race, religion, sex, marital status, and age.  <br />
    Typically,  installment lenders will be looking for stronger credit customers for their  approval process because the interest rates are generally lower and the  repayment terms are generally spaced longer out than a typical short term cash  loan or a payday loan.</p>
<p>  </p>
<p><strong><u>Payday  loans</u></strong><br />
    <br />
    <strong>How Payday Loans Work</strong><br />
    A payday loan typically has  more liberal underwriting standards than an installment loan. Generally  speaking, lenders require the consumer to be 18 and over, have a steady source  of income, and direct deposit be set up on their bank account in order to  transfer funds and payments – but specific lender requirements depend on the  individual lender. Typically these short-term cash loans are from $100 - $1,000  and come without a security deposit, credit checks or complex paperwork. </p>
<p>The information provided on  your online loan profile determines the amount you can borrow and the loan  terms based on the lenders underwriting.</p>
<p>If approved, lenders will wire  up to $1000 into the borrower's checking or savings account. At some future  date (almost always the date the borrower receives their next paycheck) the  lender will debit some amount (either the full amount or just the loan fee, as  determined by your loan agreement).</p>
<p>In order to be qualified by a  lender, a borrower provides basic information such as: their name, address,  phone number and email address. Additional questions such as their employment  and bank details help lenders determine how much someone can borrow. Private  information such as the borrower's birth date and social security number is  required to comply with the US Patriot Act.<br />
    <br />
    <strong>How much do payday loans cost</strong><br />
    This website does not charge a  fee to consumers for using our matching service, including no loan application  fee. Once you have been matched and approved by your lender, you will be  presented with your lender's terms, which you should review carefully. You will  only be charged a fee if you <strong>accept</strong> the loan offered by your lender and  if they charge a fee. Your loan terms, including fees and repayment terms, vary  from lender to lender. <strong>You are under no obligation to accept their terms</strong>,  and may accept or decline the loan at that time.<br />
    <br />
    <strong>What to expect by applying for a payday loan online</strong><br />
    First  you create your profile with our free no obligation matching service. We will  show your profile to multiple lenders and match you with the best offer for  your situation. The lender will then determine if you match their lending  criteria. This approval process takes only a few seconds. If approved, you will  be presented with the lender's terms and conditions. Each lender is required to  provide you, the consumer, with all costs associated to be expressed as an  annual percentage rate of interest (APR). This information will include  the identity of the creditor, the amount financed, the itemization of amount  financed, the finance charge, the annual percentage rate, your payment  schedule, and your total number of payments. Your interest rate will vary  depending upon which product you select from which lender -- Currently  this range is anywhere from 20% up to 1200% APR for payday loans. In addition,  the Federal Equal Credit Opportunity Act prohibits creditors from discriminating  against applicants on the basis of color, race, religion, sex, marital status,  and age. Once you read about your specific  APR and terms, you can decide to accept or decline the loan.<br />
    <br />
    <strong>How soon will be the money be available</strong><br />
    Once the loan is processed by  the lender, the cash will be wired to your bank account. Please be aware that  cash transfer times vary from lender to lender and transfer times may also  depend on your financial institution. You could receive your funds in  as-soon-as 1 hour or it may take a full business day.<br />
    <br />
    <strong>Will payday lenders do credit checks</strong><br />
    Payday lenders typically do no  credit checks with the three credit reporting bureaus: Experian, Equifax, or  Trans Union. For this reason, whether you have bad credit or even bankruptcy,  you are often still eligible for a payday loan. Participating lenders may,  among other things, verify your social security number and review your  information against national databases (such as Teletrack, DP Bureau or DataX)  that track consumer transactions with lending institutions.<br />
    <br />
    <strong>What are no fax payday loans?</strong><br />
    Loan approval is determined by  the strength of the information you provide. While most borrowers receive their  funds without needing to fax in any additional documentation, faxing may be  required in some circumstances.</p>
<p>  </p>
<p><strong><u>Merchandise  Credit Lines</u></strong><br />
    Merchandise  credit lines are sometimes referred to as "catalog cards" or even "shopping  cards." These are often presented to consumers that have bad credit or no  credit, and could be a great way for consumers to establish credit while  receiving purchasing power to shop for goods and merchandise with a small, or  no down payment. The consumer must purchase their items from a <strong>specific  store or website</strong> in which they have a <strong>membership</strong>. They often allow  the consumer to buy and finance with 0% interest, while paying minimum monthly  payments. These are often "unsecured" lines of credit, as they do not  require any type of security and often come with various guarantees of approval  if the consumer meets very minimum qualifications. Some have annual fees  and some credit lines do not. Some even report your line to a credit bureau and  may help you build your credit if you repay in a timely manner. Some  offer additional benefits which allow you to access your credit report and score.  Read your membership information carefully to answer your individual questions.  Merchandise credit lines are not loans, and a membership fee is required.</p>
<p>  </p>
